version: '3.8'

services:
  price-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: price-tracker-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src  # Development: mount source for live reload
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DATABASE_PATH=/app/data/price_tracker.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/database/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  price_tracker_data:
    driver: local